# Generated by Django 2.0 on 2018-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180419_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='iframe_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='streams',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
